### ISSUE TITLE
Add the ability to ping UDP ports with nmap

### ISSUE THREAD

**Issue by ondrejnedoma** [seriousm4x/UpSnap#256]
**The problem you currently have with this project**
When adding a UDP port, it shows a red status, because the way nmap works by default only discovers TCP.

**Describe the solution you'd like**
In the "ports" section of the computer options, add a little switch between TCP/UDP, and when that switch is in UDP, nmap will be spawned with -sU

**Additional context**
-sU is the UDP switch, and the command needs to run as root or sudo

**Comment by seriousm4x** [comment]
Hi,
nmap is not used to ping the port. Nmap is only used to find devices in the network when you are on the "Add" page. The TCP ping is done in go.

The problem with pinging UDP ports is that it is not reliable to ping them. The services running on the UDP ports must actively send a response. This is different with TCP. There you get an answer as soon as the connection is established.
At [uptime-kuma there was also the same suggestion](https://github.com/louislam/uptime-kuma/issues/9) and it was rejected for the same reason, because UDP is unfortunately too unreliable.

I also wanted to get away from the nmap dependency completely and implement the device scan in pure go as well. Also, in one of the last updates, the possibility was added to run UpSnap completely without root rights. This would also speak against it.
