### ISSUE TITLE
[REQUEST] Add Authentication

### ISSUE THREAD

**Issue by TaakoMagnusen** [seriousm4x/UpSnap#55]
**The problem you currently have with this project**
I'd like to expose UpSnap to the World Wide Web so i can issue WOL packets from anywhere, but i'd want authentication before i do that...

**Describe the solution you'd like**
Implement some form of authentication for viewing the dashboard and issuing commands

**Comment by ArthurSmoke** [comment]
me too

**Comment by TaakoMagnusen** [comment]
@ArthurSmoke I've decided to just use Caddy's built-in BasicAuth functionality. Since I'm using UpSnap behind my caddy reverse proxy it was really easy

**Comment by seriousm4x** [comment]
There is https://github.com/seriousm4x/UpSnap/issues/42 which is almost asking for the same.

It is possible to do this, but I am a little reluctant to do it because the shutdown command gives you root access to a container on the network. Even the smalest security flaw could lead to massive security issues.

As mentioned [here](https://github.com/seriousm4x/UpSnap/issues/48#issuecomment-1419033640), I recommend using a vpn for this. Caddy basic auth works as well, but is also [much less secure](https://security.stackexchange.com/a/990) than a vpn.

**Comment by seriousm4x** [comment]
I've added authorization and put the following in the readme:

---

## 🔒 Authorisation

**Since version 3.1 authorisation is enabled by default.**

User management is done through the PocketBase webinterface at [http://localhost:8090/\_/](http://localhost:8090/_/). This is mainly for internal use, such as within a home or corporate network. For external use please see below.

- To manage users, click the "Collections" icon on the left and select "users".
- To manage admins, click the "Settings" icon on the left and select "Admin".

Api permissions listed by user role:

| Api              | Unauthorized | Users | Admins |
| ---------------- | ------------ | ----- | ------ |
| List/Search Rule | ❌           | ✅    | ✅     |
| View Rule        | ❌           | ✅    | ✅     |
| Create Rule      | ❌           | ❌    | ✅     |
| Delete Rule      | ❌           | ❌    | ✅     |
| Manage Rule      | ❌           | ❌    | ✅     |
| Wake devices     | ❌           | ✅    | ✅     |
| Shutdown devices | ❌           | ✅    | ✅     |
| Scan network     | ❌           | ❌    | ✅     |

## 🌍 Exposing to the open web

Although UpSnap has user authorisation, it is **not recommended to expose it to the open web** and make it accessible by everyone!

**Reason**: The shutdown device command is basically a command piped to #sh (root if you run docker). If anyone gains unauthorized access and can abuse this api route in any way, the attacker has access to a (root) shell on your local network.

**Recommended**: If you need access from outside your network, please use a vpn. Wireguard or OpenVPN is your way to go.
