### ISSUE TITLE
[Bug] Interface not updating correctly

### ISSUE THREAD

**Issue by seriousm4x** [seriousm4x/UpSnap#757]
For me it woke up two scheduled times now with lazy ping enabled. 

Not related but what I noticed now in this version (at least, can't remember this happening before):
I did notice that when trying to wake up a machine manually that the red power icon didn't change to the yellow timer. Only when refreshing the page it did. 
Then I noticed the timer counting down all the way until 0 and it returned to the yellow timer at 2 mins. It stayed there while the machine I woke up is responding to pings. Another refresh of the page and the icon changed to green.

<img width="415" alt="image" src="https://github.com/user-attachments/assets/f6cb376c-f5e6-4377-ad9b-761d277dc6d5">

_Originally posted by @levelsw in https://github.com/seriousm4x/UpSnap/issues/669#issuecomment-2333300770_

**Comment by seriousm4x** [comment]
I had encountered this issue before when opening the page for the first time (or after clearing all caches and cookies), logging in, and immediately pressing the wake button, the yellow timer wouldn't appear. Fortunately, that issue is now resolved.

> Then I noticed the timer counting down all the way until 0 and it returned to the yellow timer at 2 mins. It stayed there while the machine I woke up is responding to pings. Another refresh of the page and the icon changed to green.

I hadn't noticed this behavior before. Could you provide more details on how I can reproduce this issue?

**Comment by levelsw** [comment]
I tried it again and everything just worked fine. Restarted the container and it also just worked fine. Will test it out again at a later moment

**Comment by rockerbacon** [comment]
I'm running into the same problem. In my case the updates just seem intermittent, not working most of the time.

I'm seeing a request to `/api/realtime` that never finishes and I can't see any network activity in the browser inspection tab that would suggest the interface is trying to get any updates - no polling requests and no WebSocket connections.

**Comment by seriousm4x** [comment]
> I'm seeing a request to `/api/realtime` that never finishes and I can't see any network activity in the browser inspection tab that would suggest the interface is trying to get any updates - no polling requests and no WebSocket connections.

This is expected. UpSnap doesn't use websockets, it uses SSE (server sent events). The `/api/realtime` endpoint will never finish because this is the connection which receives the changes.

**Comment by seriousm4x** [comment]
Anyone still having this issue with version 4.3.2 or later? If so, please tell me how I can reproduce it.

**Comment by mercurial-moon** [comment]
I'm facing a similar issue. Upsnap version 4.6.1 running on windows 10.
i start upsnap using the following command.

`upsnap.exe serve --http=0.0.0.0:8090`

Then from another pc on my LAN i access upsnap via the browser and try to turn on a device that works. But the UI doesn't update and its stuck on 2.00 min instead of counting down. In the browser console I can see 1 error 

`http://x.x.x.x:8090/api/realtime was interrupted while the page was loading`

and on the other pc where upsnap is running i see errors, but the console is not scrolling
`[ERROR] 2025/02/25 xx:xx;xx ping.go:33 listen ip4:icmp : socket: An attempt was made to access a socket in a way forbidden by its access permissions.`
